insert into proveedor (nombreProveedor) values ('Promoviendo Tu Futuro  S.A. De C.V.')
insert into proveedor (nombreProveedor) values ('Promotora De Proyectos Legacy  S.A. De C.V.')
insert into proveedor (nombreProveedor) values ('Tc Laref  S.A. De C.V.')
insert into proveedor (nombreProveedor) values ('Financiera Amigo  S.A. De C.V.')
insert into proveedor (nombreProveedor) values ('Arca Financiera Para El Futuro  S.A. De C.V.')
insert into proveedor (nombreProveedor) values ('Podemos Progresar  S.A.P.I. De C.V.')
insert into proveedor (nombreProveedor) values ('Sistema De Microcréditos Mac  S.A.P.I. De C.V.')
insert into proveedor (nombreProveedor) values ('Proyección Económica Y Empresarial  S.A. De C.V.')
insert into proveedor (nombreProveedor) values ('Sf + Vc México  S.A.P.I. De C.V.')
insert into proveedor (nombreProveedor) values ('Confianza Económica  S.A. De C.V.')
